name: Coverage

on: ["push"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Install dev dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Build unit coverage using pytest-cov
      run: |
        pytest --cov=trackbench --cov-report=xml tests/trackbench/unit
        score=$(python coverage_score.py --score)
        color=$(python coverage_score.py --color)
        echo "COVERAGE_UNIT_SCORE=$score"
        echo "COVERAGE_UNIT_COLOR=$color"
        echo "COVERAGE_UNIT_SCORE=$score" >> $GITHUB_ENV
        echo "COVERAGE_UNIT_COLOR=$color" >> $GITHUB_ENV
    - name: Create unit coverage badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 8971164299ef4415d92fbb6b9fc81744
        filename: pyflow_unit_coverage_badge.json
        label: Unit Coverage
        message: ${{ env.COVERAGE_UNIT_SCORE }}
        color: ${{ env.COVERAGE_UNIT_COLOR }}
        style: plastic